/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import static form.FormMode.NEW;
import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.Image;
import java.net.URL;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Tamarica
 */
public class FrmMain extends javax.swing.JFrame {

    private FrmAddMember frmAddMember;
    private FrmReview frmReview;
    private FrmAddPublication frmAddPublication;

    public FrmMain() {
        initComponents();
        centerForm();
        setDimension();
        addImage();
//        maxForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBarMain = new javax.swing.JMenuBar();
        jMenuMember = new javax.swing.JMenu();
        jMenuItemAddMember = new javax.swing.JMenuItem();
        jMenuItemReviewMembers = new javax.swing.JMenuItem();
        jMenuItemLiabilities = new javax.swing.JMenuItem();
        jMenuPublication = new javax.swing.JMenu();
        jMenuItemAddPublication = new javax.swing.JMenuItem();
        jMenuItemReviewPublications = new javax.swing.JMenuItem();
        jMenuPublisher = new javax.swing.JMenu();
        jMenuItemAddPublisher = new javax.swing.JMenuItem();
        jMenuItemReviewPublishers = new javax.swing.JMenuItem();
        jMenuItemPurchaseOrder = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome!");
        setLocation(new java.awt.Point(500, 700));

        jMenuMember.setText("Members");

        jMenuItemAddMember.setText("Enrollment");
        jMenuItemAddMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddMemberActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemAddMember);

        jMenuItemReviewMembers.setText("Review");
        jMenuItemReviewMembers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReviewMembersActionPerformed(evt);
            }
        });
        jMenuMember.add(jMenuItemReviewMembers);

        jMenuItemLiabilities.setText("Liabilities");
        jMenuMember.add(jMenuItemLiabilities);

        jMenuBarMain.add(jMenuMember);

        jMenuPublication.setText("Publications");

        jMenuItemAddPublication.setText("New");
        jMenuItemAddPublication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAddPublicationActionPerformed(evt);
            }
        });
        jMenuPublication.add(jMenuItemAddPublication);

        jMenuItemReviewPublications.setText("Review");
        jMenuPublication.add(jMenuItemReviewPublications);

        jMenuBarMain.add(jMenuPublication);

        jMenuPublisher.setText("Publishers");

        jMenuItemAddPublisher.setText("New");
        jMenuPublisher.add(jMenuItemAddPublisher);

        jMenuItemReviewPublishers.setText("Review");
        jMenuPublisher.add(jMenuItemReviewPublishers);

        jMenuItemPurchaseOrder.setText("Purchase order");
        jMenuPublisher.add(jMenuItemPurchaseOrder);

        jMenuBarMain.add(jMenuPublisher);

        setJMenuBar(jMenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAddMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddMemberActionPerformed
        frmAddMember = new FrmAddMember(this, true, NEW);
        frmAddMember.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddMemberActionPerformed

    private void jMenuItemReviewMembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReviewMembersActionPerformed
        frmReview = new FrmReview(this, true);
        frmReview.setVisible(true);
    }//GEN-LAST:event_jMenuItemReviewMembersActionPerformed

    private void jMenuItemAddPublicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAddPublicationActionPerformed
        frmAddPublication = new FrmAddPublication(this, true, NEW);
        frmAddPublication.setVisible(true);
    }//GEN-LAST:event_jMenuItemAddPublicationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarMain;
    private javax.swing.JMenuItem jMenuItemAddMember;
    private javax.swing.JMenuItem jMenuItemAddPublication;
    private javax.swing.JMenuItem jMenuItemAddPublisher;
    private javax.swing.JMenuItem jMenuItemLiabilities;
    private javax.swing.JMenuItem jMenuItemPurchaseOrder;
    private javax.swing.JMenuItem jMenuItemReviewMembers;
    private javax.swing.JMenuItem jMenuItemReviewPublications;
    private javax.swing.JMenuItem jMenuItemReviewPublishers;
    private javax.swing.JMenu jMenuMember;
    private javax.swing.JMenu jMenuPublication;
    private javax.swing.JMenu jMenuPublisher;
    // End of variables declaration//GEN-END:variables

    public FrmAddMember getFrmAddMember() {
        return frmAddMember;
    }

    public FrmReview getFrmReview() {
        return frmReview;
    }

    private void maxForm() {
        setExtendedState(MAXIMIZED_BOTH);
    }

    private void centerForm() {
        setLocationRelativeTo(null);
    }

    private void setDimension() {

        setLocation(300, 150);
        setSize(1000, 600);
        setResizable(false);
    }

    private void addImage() {
//     ImageIcon imageIcon = new ImageIcon(getClass().getResource("/view/biblioteka.jpg"));
//
//        if (imageIcon.getIconWidth() == -1) {
//            System.out.println("Image not loaded. Check the path.");
//        }
//        //ImageIcon imageIcon = new ImageIcon("D:\\PS projekti\\Biblioteka\\Client\\biblioteka.jpg");     // D:\PS projekti\Biblioteka\Client\biblioteka.jpg
//        JLabel imageLabel = new JLabel(imageIcon);
//        this.add(imageLabel);
//       this.revalidate();
//        this.repaint();

        URL imageUrl = getClass().getResource("/img/biblioteka-slika.jpg");
        if (imageUrl == null) {
            System.out.println("Image resource not found. Check the path.");
        } else {
            ImageIcon imageIcon = new ImageIcon(imageUrl);
            Image image = imageIcon.getImage();
            Image resizedImage = image.getScaledInstance(1000, 600, Image.SCALE_SMOOTH);
            ImageIcon resizedIcon = new ImageIcon(resizedImage);
            JLabel imageLabel = new JLabel(resizedIcon);
            this.setLayout(new FlowLayout());
            this.add(imageLabel, BorderLayout.CENTER);
            this.revalidate();
            this.repaint();
        }
    }

    public FrmAddPublication getFrmAddPublication() {
        return frmAddPublication;
    }
}
